### ISSUE TITLE
应该把handleDelete的事件开放出来

### ISSUE THREAD

**Issue by 2999** [tinglejs/tingle-search-bar#2]
如题

**Comment by gbk** [comment]
希望做哪些处理呢？delete 的时候会把内容置空同时触发 onChange 事件，外面可以知道是内容清空了

**Comment by 2999** [comment]
其实我是想拿到搜索关闭的事件（失焦 + val为空），当用户取消搜索的时候，我可以做些其它操作

**Comment by gbk** [comment]
清空内容焦点仍然在输入框里，并不会触发失焦的，取消搜索到底是什么操作呢？
