### ISSUE TITLE
通过 props 赋值不会清除 placeholder

### ISSUE THREAD

**Issue by gbk** [tinglejs/tingle-search-bar#4]
通过 props 去修改 input 的 value 不会触发 onChange 事件，导致 empty 状态的判断不同步。

**Comment by lpgray** [comment]
@gbk 啥时候 Salt 开源到 github 上来啊，等待刷 push 呢

**Comment by gbk** [comment]
等 @alex.mm 的回归呢，我本来也是不建议挪内网去的…… 来回折腾 唉
